name: bible_book_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  hive: ^2.2.3
  http: ^1.1.0
  hive_flutter: ^1.1.0
  sizer: ^2.0.15
  connectivity_plus: ^5.0.1
  line_icons: ^2.0.3
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  expandable_page_view: ^1.0.17
  shared_preferences: ^2.2.2
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.4




dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/books/exodus/
    - assets/images/
    - assets/db/
  fonts:
    - family: Abyssinica
      fonts:
        - asset: assets/fonts/AbyssinicaSIL-Regular.ttf


